const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  accessToken: state => state.user.accessToken,
  companyId: state => state.user.companyId,
  companyName: state => state.user.companyName,
  companyType: state => state.user.companyType,
  username: state => state.user.username,
  email: state => state.user.email,
  sex: state => state.user.sex,
  tokenType: state => state.user.tokenType,
  refreshToken: state => state.user.refreshToken,
  name: state => state.user.name,
  roles: state => state.user.roles,
  userId: state => state.user.userId,
  setting: state => state.user.setting,
  permission_routers: state => state.permission.routers,
  authMenus: state => state.permission.authMenus,
  addRouters: state => state.permission.addRouters,
  errorLogs: state => state.errorLog.logs,
  merchant: state => state.user.merchant,
  treelist: state => state.treelist,
  secretKey: state => state.user.secretKey,
  iv: state => state.user.iv,
  fileSelectData:state => state.user.fileSelectData,
  riskSelectData:state => state.user.riskSelectData,
  testSelectData:state => state.user.testSelectData,
  missionSelectData:state => state.user.missionSelectData,
  failSelectData:state => state.user.failSelectData,
  defectSelectData:state => state.user.defectSelectData,
  userSelectData:state => state.user.userSelectData,
  userProductSelectData:state => state.user.userProductSelectData,
  navList:state => state.user.navList,//判断权限列表
  colList:state => state.user.colList,//左侧列表
  permissionState:state => state.user.permissionState,//用户系统使用状态
  permissionTime:state => state.user.permissionTime,//用户系统过期时间
  encryptOpen:state => state.user.encryptOpen,//是否开启加密
  notEncUrls:state => state.user.notEncUrls,//加密白名单
  approvalTaskMsg:state => state.user.approvalTaskMsg,//立项暂存导入信息
  customerTaskMsg:state => state.user.customerTaskMsg,//客户暂存导入信息
  saleplanTaskMsg:state => state.user.saleplanTaskMsg,//销售计划暂存导入信息
  orderScroll:state => state.listLoad.orderScroll,//暂存订单列表离开页面时所在位置
  orderPage:state => state.listLoad.orderPage,//暂存订单分页
  contractScroll:state => state.listLoad.contractScroll,//暂存合同列表离开页面时所在位置
  contractPage:state => state.listLoad.contractPage,//暂存合同分页
  salePlanScroll:state => state.listLoad.salePlanScroll,//暂存销售计划列表离开页面时所在位置
  salePlanPage:state => state.listLoad.salePlanPage,//暂存销售计划分页
  customerScroll:state => state.listLoad.customerScroll,//暂存客户列表离开页面时所在位置
  customerPage:state => state.listLoad.customerPage,//暂存客户分页
  performanceScroll:state => state.listLoad.performanceScroll,//绩效管理
  performancePage:state => state.listLoad.performancePage,//绩效管理
  messageSendScroll:state => state.listLoad.messageSendScroll,//信息群发
  messageSendPage:state => state.listLoad.messageSendPage,//信息群发
  patentScroll:state => state.listLoad.patentScroll,//专利列表
  patentPage:state => state.listLoad.patentPage,//专利列表
  copyrightScroll:state => state.listLoad.copyrightScroll,//著作权列表
  copyrightPage:state => state.listLoad.copyrightPage,//著作权列表
  trademarkScroll:state => state.listLoad.trademarkScroll,//商标列表
  trademarkPage:state => state.listLoad.trademarkPage,//商标列表
  certificateScroll:state => state.listLoad.certificateScroll,//证书列表
  certificatePage:state => state.listLoad.certificatePage,//证书列表
  policyScroll:state => state.listLoad.policyScroll,//政策列表
  policyPage:state => state.listLoad.policyPage,//政策列表
  projectScroll:state => state.listLoad.projectScroll,//项目列表
  projectPage:state => state.listLoad.projectPage,//项目列表
  approvalScroll:state => state.listLoad.approvalScroll,//立项列表
  approvalPage:state => state.listLoad.approvalPage,//立项列表
  publicityResultScroll:state => state.listLoad.publicityResultScroll,//公示列表
  publicityResultPage:state => state.listLoad.publicityResultPage,//公示列表
  declareScroll:state => state.listLoad.declareScroll,//申报管理列表
  declarePage:state => state.listLoad.declarePage,//申报管理列表
  fileTypeScroll:state => state.listLoad.fileTypeScroll,//文件分类
  fileTypePage:state => state.listLoad.fileTypePage,//文件分类
  listLoad:state => state.listLoad.listLoad,//判断页面是否刷新
  newMessage:state => state.saveState.newMessage,// 新消息提示
  publicDer:state => state.user.publicDer,// 前端生成的公钥
  privateDer:state => state.user.privateDer,// 前端生成的私钥
  singleCapacity:state => state.user.singleCapacity,// 单个文件上传限制的大小
  totalCapacity:state => state.user.totalCapacity,// 服务器剩余容量大小
}

export default getters
